// example of custom API
import groovy.json.JsonSlurperClassic 

@NonCPS
def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}

def repo = "AndrewKorell/jenkins-course"

def token = httpRequest authentication: 'github_api', contentType: 'APPLICATION_FORM', httpMode: 'POST', requestBody: 'grant_type=client_credentials', 
    url: 'https://github.com/login/oauth/access_token'
    client_id: 'github_api.username'
    code: '71d83cf98cdf9a8afdc1'
    redirect_uri: 'http://138.197.148.156:8080'
    header: 'Accept: application/vnd.github+json'
    
def accessToken = jsonParse(token.content).access_token
def pr = httpRequest customHeaders: [[maskValue: true, name: 'Authorization', value: 'Bearer ' + accessToken]], url: "https://api.github.com/repos/${owner}/${repo}/pulls"

for (p in jsonParse(pr.content).values) { 
    println(p.source.branch.name)
}
